/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Metodos.Inserts;
import Metodos.Listas;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author carlos
 */
public final class AltaCliente extends javax.swing.JDialog {

    //istancia de Listas
    Listas l = new Listas();
    //Icono de la App
    ImageIcon icon2 = new ImageIcon("imagenes\\icono.png");
    
    Inserts i = new Inserts();

    public AltaCliente(java.awt.Frame parent, boolean modal) {

        super(parent, modal);
        initComponents();
        // Icono cliente
        //icono app
        this.setIconImage(icon2.getImage());
        //Vaciando los Campos
        aTf1.setText(null);
        aTf2.setText(null);
        aTf3.setText(null);
        aTf4.setText(null);
        aTf5.setText(null);
        setLocationRelativeTo(null);
        rellenarPaises();

    }

    public void rellenarPaises() {

        for (int i = 0; i < l.getPaises().length; i++) {
            String[] x = l.getPaises();
            jCbPaises.addItem(x[i]);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aTf1 = new javax.swing.JTextField();
        aTf3 = new javax.swing.JTextField();
        aTf2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        aTf4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCbPaises = new javax.swing.JComboBox();
        aTf5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        cliente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nuevo Cliente");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        aTf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTf1ActionPerformed(evt);
            }
        });
        jPanel1.add(aTf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 33, 107, -1));
        jPanel1.add(aTf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 137, 107, -1));

        aTf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aTf2ActionPerformed(evt);
            }
        });
        jPanel1.add(aTf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 59, 107, -1));

        jLabel1.setText("Nombre:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 39, -1, -1));

        jLabel2.setText("DNI:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 65, 41, -1));

        jLabel3.setText("Telefono:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        jLabel4.setText("Direccion:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));
        jPanel1.add(aTf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 107, -1));

        jLabel5.setText("E-mail:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 88, -1, -1));

        jLabel6.setText("Pais");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 117, -1, -1));

        jCbPaises.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCbPaisesActionPerformed(evt);
            }
        });
        jPanel1.add(jCbPaises, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 111, 107, -1));
        jPanel1.add(aTf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 85, 107, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/tick.png"))); // NOI18N
        jButton1.setText("Aceptar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 103, 36));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cross.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 220, 110, 36));

        jLabel8.setText("Datos del Cliente");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        cliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cliente.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(cliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");
        getAccessibleContext().setAccessibleParent(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aTf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTf1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTf1ActionPerformed

    private void aTf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aTf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aTf2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        aTf1.setText("");
        aTf2.setText("");
        aTf3.setText("");
        aTf4.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        boolean x = false;
        do {
            try {
                x = true;
                // Aqui verificamos que los datos son correctos y creamos un Insert
                String nombre = aTf1.getText();
                String dni = aTf2.getText();
                int phone = Integer.parseInt(aTf3.getText());
                String dir = aTf4.getText();
                String email = aTf5.getText();
                String pais = jCbPaises.getSelectedItem().toString();

                Main.conexion.update(i.nuevoCliente(dni, nombre, pais, email, phone, dir));
                
            } catch (SQLException ex) {
                x = false;
                int eCode = ex.getErrorCode();
                if (eCode == 0) {
                    JOptionPane.showMessageDialog(rootPane, "Ya existe ese DNI en la Base de Datos");
                }
            } catch (NumberFormatException ole) {
                x = false;
                JOptionPane.showMessageDialog(rootPane, "Debes Introducir un Numero de Telefono Valido");
            }
        } while (x = false);
        if(x=true){
            
        JOptionPane.showMessageDialog(rootPane, "Cliente Creado Satisfactoriamente", "Completado", JOptionPane.INFORMATION_MESSAGE);
        this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCbPaisesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCbPaisesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCbPaisesActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField aTf1;
    private javax.swing.JTextField aTf2;
    private javax.swing.JTextField aTf3;
    private javax.swing.JTextField aTf4;
    private javax.swing.JTextField aTf5;
    private javax.swing.JLabel cliente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jCbPaises;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
